inherit_from: .rubocop_todo.yml

# Be lenient with line length
Layout/LineLength:
  Max: 92

# In guard clauses, if ! is often more immediately clear
Style/NegatedIf:
  Enabled: false

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets
