# frozen_string_literal: true

# HACK: This uses odd syntax to make appraisal customization work on newer Rubies.
# See https://github.com/thoughtbot/appraisal/pull/214. Once that one has been
# released, we should use customize_gemfiles instead.
Customize.new heading: <<~HEADING.chomp
  frozen_string_literal: true

  This file was generated by Appraisal
HEADING

appraise "active_record_72" do
  gem "activerecord", "~> 7.2.0", require: "active_record"
  gem "activesupport", "~> 7.2.0", require: "active_support"

  group :development do
    gem "activerecord-jdbcsqlite3-adapter", "~> 72.0", platforms: [:jruby]
    gem "sqlite3", "~> 2.0", platforms: [:ruby]
  end
end

appraise "active_record_80" do
  gem "activerecord", "~> 8.0.0", require: "active_record"
  gem "activesupport", "~> 8.0.0", require: "active_support"

  group :development do
    gem "sqlite3", "~> 2.0", platforms: [:ruby]
  end
end

appraise "active_record_81" do
  gem "activerecord", "~> 8.1.0", require: "active_record"
  gem "activesupport", "~> 8.1.0", require: "active_support"

  group :development do
    gem "sqlite3", "~> 2.0", platforms: [:ruby]
  end
end
