name: Automerge dependency updates

on: [pull_request]
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      github.actor == 'dependabot[bot]'
    steps:
      - name: "@dependabot merge"
        uses: actions/github-script@v3
        with:
          script: |
            const title = context.payload.pull_request.title;
            const update_regex = /Update [^ ]* requirement from ~> ([1-9][0-9]*)\.\d+\.\d+ to ~> \1\.\d+\.\d+/;
            const update_match = title.match(update_regex);

            if (update_match !== null) {
              console.log(`Detected allowed update in '${title}'`);
            } else {
              return;
            }

            github.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
